In [1]:
import numpy as np

In [2]:
lst=[2,5,7,8]

In [3]:
np.array(lst)

array([2, 5, 7, 8])

In [5]:
np.array([lst,lst])

array([[2, 5, 7, 8],
       [2, 5, 7, 8]])

In [8]:
np.eye(3)*8

array([[8., 0., 0.],
       [0., 8., 0.],
       [0., 0., 8.]])

In [10]:
np.zeros(shape=(4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [11]:
5*np.ones(shape=(3,5))

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(-5,10,2)

array([-5, -3, -1,  1,  3,  5,  7,  9])

In [16]:
np.arange(100,9,-5)

array([100,  95,  90,  85,  80,  75,  70,  65,  60,  55,  50,  45,  40,
        35,  30,  25,  20,  15,  10])

In [34]:
np.linspace(0,100,4)

array([ 0., 25., 50., 75.])

In [35]:
mat=np.random.randn(3,4)
mat

array([[ 0.51881149,  0.76703932,  0.05187704, -0.64704105],
       [ 0.48786874,  1.31923949,  0.30244854,  0.51563811],
       [-0.58374238, -0.71158095, -0.02069519, -0.03503401]])

In [31]:
type(mat)

numpy.ndarray

In [32]:
mat.size

8

In [33]:
np.random.randint(10,20,5)

array([14, 13, 11, 19, 14])

In [36]:
mat.reshape(2,6)

array([[ 0.51881149,  0.76703932,  0.05187704, -0.64704105,  0.48786874,
         1.31923949],
       [ 0.30244854,  0.51563811, -0.58374238, -0.71158095, -0.02069519,
        -0.03503401]])

In [41]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print((arr[1,1:4]))

10
